### PR TITLE
Add Music.json

### PR DESCRIPTION
**Pull request by dtalbot1984**

### CODE REVIEW

**Comment by shadowkora** [comment]
Please add your policyID to your Twitter bio, I also couldn't help but notice that your website is empty @dtalbot1984

**Comment by dtalbot1984** [comment]
> Please add your policyID to your Twitter bio, I also couldn't help but notice that your website is empty @dtalbot1984

Hi there, It is not my token as such.. The token founder https://twitter.com/rasta_ada?s=11&t=1xM0kbEuOmWI8ZsBVUPn4Q has the Policy ID in the Twitter BIO.. I was not aware about the need for a website as well, many Verified Projects seem to be fine with just Twitter Link... Is there anything else i need to know? 

Policy ID as per both Founders Twitter BIO and this Commit is 50009ca6291a2d1069bfb8d01dd2776401fe5d767f603b6cee55ab01

Thanks

**Comment by shadowkora** [comment]
> > Please add your policyID to your Twitter bio, I also couldn't help but notice that your website is empty @dtalbot1984
> 
> Hi there, It is not my token as such.. The token founder https://twitter.com/rasta_ada?s=11&t=1xM0kbEuOmWI8ZsBVUPn4Q has the Policy ID in the Twitter BIO.. I was not aware about the need for a website as well, many Verified Projects seem to be fine with just Twitter Link... Is there anything else i need to know?
> 
> Policy ID as per both Founders Twitter BIO and this Commit is 50009ca6291a2d1069bfb8d01dd2776401fe5d767f603b6cee55ab01
> 
> Thanks

This PR is regarding the MUSIC token, not the RASTA token, and the twitter for the MUSIC token doesn't have the policyID on it.

**Comment by dtalbot1984** [comment]
> > > Please add your policyID to your Twitter bio, I also couldn't help but notice that your website is empty @dtalbot1984
> > 
> > 
> > Hi there, It is not my token as such.. The token founder https://twitter.com/rasta_ada?s=11&t=1xM0kbEuOmWI8ZsBVUPn4Q has the Policy ID in the Twitter BIO.. I was not aware about the need for a website as well, many Verified Projects seem to be fine with just Twitter Link... Is there anything else i need to know?
> > Policy ID as per both Founders Twitter BIO and this Commit is 50009ca6291a2d1069bfb8d01dd2776401fe5d767f603b6cee55ab01
> > Thanks
> 
> This PR is regarding the MUSIC token, not the RASTA token, and the twitter for the MUSIC token doesn't have the policyID on it.

I am so sorry i didn't even realise i had sent the request in for MUSIC Token yet. Will add the policy ID now, but the Website is not ready for publishing yet, so will remove. Thanks.

**Comment by shadowkora** [comment]
I also noticed this token doesn't have a pool yet so I can't merge the PR, but please do tag me when you launch the token pool and I will merge it @dtalbot1984

**Comment by shadowkora** [comment]
@dtalbot1984 Is this still relevant or can I close this PR? (I will close it in 24h if there is no reply)

**Pull request closed without merging**
