### PR TITLE
Rosen Bridge Wrapped Tokens

### PR DESCRIPTION
**Pull request by glasgowm148**
Not sure if I've done this correctly, couldn't see other examples with multiple assets using the one policyID, let me know.

### CODE REVIEW

**Comment by glasgowm148** [comment]
https://github.com/rosen-bridge/contract/releases/download/2.0.1/tokensMap-public-launch-2.0.1.json

https://twitter.com/RosenBridge_erg/status/1742259034936484136

**Comment by shadowkora** [comment]
Hey @glasgowm148, for multiple assets using the same policyID you only need to make verified for one token, then the socials will be shared across all the tokens with the same policyID

**Comment by glasgowm148** [comment]
> Hey @glasgowm148, for multiple assets using the same policyID you only need to make verified for one token, then the socials will be shared across all the tokens with the same policyID
> 
> If you check the first entry in tokens (Minswap) you will see that it verifies MIN and MINt

Hmm but each token will have a different social?

**Comment by shadowkora** [comment]
No pool exists for rsSigRSV

**Pull request closed without merging**
