### PR TITLE
tokens.json

### PR DESCRIPTION
**Pull request by Kraphene**

### CODE REVIEW

**Comment by tvtduy59** [comment]
@Kraphene it looks good, can you resolve the conflicts?

**Comment by Kraphene** [comment]
thanks

**Comment by tvtduy59** [comment]
Hi @Kraphene , sorry for the late response. The CI failed because of "Audit" and "Social" items in the categories. I added "Social" into the base categories, but the "Audit" we've wanted to have it now. So, can you update the PR?

**Comment by shadowkora** [comment]
Added in #387

**Pull request closed without merging**
