### PR TITLE
Add ladao to Tokens.json

### PR DESCRIPTION
**Pull request by AdirkAda**
},
"4995b8a6bb4604585eae28b8155afc3b346c751756c72562861cdc76": {
    "project": "LOTTO",
    "categories": ["NFT", "GameFi"],
    "socialLinks": {
      "website": "https://www.ladao.pro",
      "twitter": "https://twitter.com/dmoney699315",
      "discord": "https://discord.com/invite/dirk_39726"
    }
  }
}

### CODE REVIEW

**Comment by shadowkora** [comment]
Pool with the token with this policyID doesn't exist

**Comment by AdirkAda** [comment]
> Pool with the token with this policyID doesn't exist



Sorry, Im fixing it with the correct one, thanks.

820182018282051a0691bcd58200581c39a1df51147b6de6689a4727846962fb6540c3a3c7859a1a79b9420f

**Comment by AdirkAda** [comment]
updated policy ID, ty

**Comment by AdirkAda** [comment]
> Pool with the token with this policyID doesn't exist
updated to correct policy ID*.  ty

**Comment by shadowkora** [comment]
@AdirkAda You're creating a new file but you need to modify tokens.json instead

**Comment by AdirkAda** [comment]
> @AdirkAda You're creating a new file but you need to modify tokens.json instead

I believe I modified tokens.json correctly? if not could you please let me know what im doing wrong?  
thank you so much.

**Comment by shadowkora** [comment]
@AdirkAda Can you fix your socials? Both Discord invite and the website are invalid

**Pull request closed without merging**
