### PR TITLE
Add BUY token

### PR DESCRIPTION
**Pull request by dnb-reg**

### CODE REVIEW

**Comment by shadowkora** [comment]
Hey @dnb-reg, your token is missing a logo in the cardano-token-registry, until you address this I can't verify you.

**Comment by dnb-reg** [comment]
Hey @shadowkora apologies for jumping the gun yesterday, the CF reg wasn't verified yet. It's good to go now!

https://github.com/cardano-foundation/cardano-token-registry/pull/3474

**Comment by dnb-reg** [comment]
Hello, 4 days have past now, when could we expect a revision/verification please?

**Comment by dnb-reg** [comment]
@shadowkora I pushed at the time I did in an attempt to have the approval done quickly, I apologize for the pending image oversight but it has been two weeks now. Please update us?

**Comment by shadowkora** [comment]
@dnb-reg You didn't put the image as a Byte String in the Cardano Token Registry
vvcap 2023-09-06-11-06-52

Until it has the logo, I won't verify it.

**Comment by dnb-reg** [comment]
@shadowkora Done, approved and checked on minswap. Please update at your earliest convenience. It was a miscommunication and an original issue with the json generation.

**Comment by shadowkora** [comment]
Added in #462

**Pull request closed without merging**
