### PR TITLE
Updated tokens.json with AWOO

### PR DESCRIPTION
**Pull request by 3000dev**
Added $AWOO as a token.

### CODE REVIEW

**Comment by 3000dev** [comment]
https://www.unbotheredwolves.com/awoo

This is the part of the website for the token

**Comment by theuranus** [comment]
Hi @3000dev , your PR is invalid, the CI ran failed ( might be not in JSON format). Please fix it first

**Comment by theuranus** [comment]
> Hey @theuranus, I have changed the file and validated with a json validator to be sure!

Still fail and your PR changed whole the file. See [file changes ](https://github.com/minswap/verified-tokens/pull/55/files)

**Review by 3000dev — COMMENTED** [review]
Shall I delete this PR and submit a new one? I tried editing the original commit to simply add the missing bracket.

**Comment by 3000dev** [comment]
Thank you @theuranus, would you be kind enough to ping me to check when it is finished, please? Appreciate your support!

**Pull request closed without merging**
