### PR TITLE
GaryTheClown submission

### PR DESCRIPTION
**Pull request by DonGuennie**
Please verfied the GaryTheClown - Token... Thank youuuuuuuuuuu

### CODE REVIEW

**Comment by DonGuennie** [comment]
{
  "$policyId": {
    "project": $GaryCBDC,
    "categories": string[Meme], 
    "socialLinks"?: {
      "website"?: No Website,
      "twitter"?: No Twitter,
      "discord"?: No Discord,
      "telegram"?: No Telegram,
      "coinMarketCap"?: unkown,
      "coinGecko"?: unkown
    }
  }
}

**Comment by DonGuennie** [comment]
{
"$policyId": {
"project": $GaryCBDC,
"categories": string[Meme],
"socialLinks"?: {
"website"?: www.tokensyndicate.de,
"twitter"?: https://twitter.com/TokenSyndicate,
"discord"?: No Discord,
"telegram"?: No Telegram,
"coinMarketCap"?: unkown,
"coinGecko"?: unkown
}
}
}

**Comment by shadowkora** [comment]
@DonGuennie Can you please fix your PR and make it in our format?
If you are unsure please make an issue instead of a PR, you also didn't share your policyID in the above text and you're missing your token policyID on your socials as well, so address these two points please.

**Comment by DonGuennie** [comment]
{
"$policyId": {6106ab6d8912a8f7e08b5d3300d5f8bdd6371793caceee7e08598685
"project": $GaryCBDC,
"categories": string[Meme],
"socialLinks"?: {
"website"?: [www.tokensyndicate.de](http://www.tokensyndicate.de/),
"twitter"?: https://twitter.com/TokenSyndicate,
"discord"?: No Discord,
"telegram"?: No Telegram,
"coinMarketCap"?: unkown,
"coinGecko"?: unkown
}
}
}

**Pull request closed without merging**
