### PR TITLE
Update tokens.json

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
Hey, Minswap 

Just adding Point Of View (POV) in ;)

### CODE REVIEW

**Comment by shadowkora** [comment]
The policyID is missing from your socials

**Comment by GabrielMazzanti** [comment]
Okay can i add it on twitter, we have some updating to do on the site

**Comment by shadowkora** [comment]
Twitter bio works, yes

**Comment by GabrielMazzanti** [comment]
Thank you, i just posted a tweet about it, and a pinned one with the
minswap link. It will soon be added on the site. I have yo see with the
owner for this :D

Thank you

**Pull request closed without merging**
