### PR TITLE
add clanity token info

### PR DESCRIPTION
**Pull request by Brave-source**

### CODE REVIEW

**Comment by Brave-source** [comment]
Please confirm and verify clan token; the policy is already on the twitter page

**Comment by shadowkora** [comment]
Twitter account is non-existent

**Comment by Brave-source** [comment]
Ohh, Here please:
https://x.com/clanityofficial?t=CcmVF3v8EKxP6vSLcOb3Yg&s=09

**Comment by Brave-source** [comment]
I have added the correct twitter link and created a new PR

**Pull request closed without merging**
