### PR TITLE
Add MILK to tokens.json

### PR DESCRIPTION
**Pull request by MuesliSwapTeam**
This PR adds the MILK token to the list of verified tokens

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Policy ID displayed here: https://docs.muesliswap.com/cardano/tokenomics/muesliswap-milk

**Comment by theuranus** [comment]
Hi @MuesliSwapTeam  😸 , There is a conflict after I merged your adding SNOW token PR. Please add the rest 2 tokens in 1 PR then I'll merge it.

**Comment by theuranus** [comment]
Hi @MuesliSwapTeam 

> Hi @MuesliSwapTeam 😸 , There is a conflict after I merged your adding SNOW token PR. Please add the rest 2 tokens in 1 PR then I'll merge it.

Hi @MuesliSwapTeam , might you miss my comment 😸

**Comment by theuranus** [comment]
Because of conflict, I added in the PR: https://github.com/minswap/verified-tokens/pull/57

**Pull request closed without merging**
