### PR TITLE
Add MUTANT token

### PR DESCRIPTION
**Pull request by glneto**

### CODE REVIEW

**Comment by tvtduy59** [comment]
@glneto The project should have a pool on our DEX 1st

**Comment by glneto** [comment]
@tvtduy59 is this what you mean?

https://app.minswap.org/swap?currencySymbolA=&tokenNameA=&currencySymbolB=ffb1abe9fe93ee9f13874403a3d4f8addaa65fbf22d5d7f41c087d8e&tokenNameB=4d5554414e54

**Comment by theuranus** [comment]
@glneto Hi, can you please resolve conflicts?

**Comment by theuranus** [comment]
@glneto hey your PR is failed CI. Look like you missed a close bracket

**Comment by glneto** [comment]
> @glneto hey your PR is failed CI. Look like you missed a close bracket

done 👍

**Review by theuranus — APPROVED** [review]

**Pull request merged**
