### PR TITLE
verify cavalier king charles

### PR DESCRIPTION
**Pull request by CharlyToken**
{
  "$policyId": 89267e9a35153a419e1b8ffa23e511ac39ea4e3b00452e9d500f2982:  {
    "project": "Cavalier King Charles token",
    "categories": ["Metaverse"],
    "socialLinks"?: {
      "website"?: "https://charly-token.io/",
      "twitter"?: "https://twitter.com/Charlytoken7",
      "discord"?: "https://discord.com/invite/ArH9udyKTN",
      "telegram"?: "https://t.me/charlytoken7"
    }
  }
}

### CODE REVIEW

**Comment by theuranus** [comment]
Thank you for contributing. However, your PR is invalid. I'll treat your PR like an issue and I'll process later :D

**Comment by CharlyToken** [comment]
> Thank you for contributing. However, your PR is invalid. I'll treat your PR like an issue and I'll process later :D

What i did wrong? Need to change anything?

**Comment by shadowkora** [comment]
You need to put the json data into the file, not in the PR description/comment.

**Comment by CharlyToken** [comment]
> You need to put the json data into the file, not in the PR description/comment.

i ll try again if now works?

**Comment by theuranus** [comment]
I'll help you verifying this token

**Comment by CharlyToken** [comment]
> I'll help you verifying this token

Ok please i m not so well known with git hub :)

**Comment by shadowkora** [comment]
Added in https://github.com/minswap/verified-tokens/pull/22

**Pull request closed without merging**
