### PR TITLE
Verify CHIP token

### PR DESCRIPTION
**Pull request by bckspaceee**

### CODE REVIEW

**Comment by bckspaceee** [comment]
Hi I see that this is closed. Can I know why? Thanks

**Comment by shadowkora** [comment]
The policyID is either invalid, or the pool doesn't exist on Minswap, both will cause you to not meet our requirements.

**Comment by bckspaceee** [comment]
Its in the V1. I'll transfer the some of the LP in the V2 if thats fine

**Comment by bckspaceee** [comment]
Hi @shadowkora this is the policy ID

f5808c2c990d86da54bfc97d89cee6efa20cd8461616359478d96b4c

If I need to submit another request please let me know thanks

**Comment by shadowkora** [comment]
The token under the policyID that you shared doesn't have a proper name and has no logo.

You don't need to submit a new PR, I will reopen this one, but please read our requirements first and make sure you meet all of them

**Comment by bckspaceee** [comment]
My bad. This is the policy ID: 30d2ebdb2fec06142ee84e5120c2717b4d68a91bffd924420d94ddea

Screenshot 2024-08-06 182955

**Comment by bckspaceee** [comment]
Hi @shadowkora please let me know if you need more information. The policy ID should be good now. Thank you!

**Comment by shadowkora** [comment]
I cannot find the token's policyID anywhere on your website or socials @bckspaceee

**Comment by bckspaceee** [comment]
Hi @shadowkora  it is now added in our website please do check this https://cardanocasino.vip/ 
image

**Pull request merged**
