### PR TITLE
FibonacciADA (FDA) Verify.

### PR DESCRIPTION
**Pull request by FibonacciADA**
Thank you :)

### CODE REVIEW

**Comment by shadowkora** [comment]
You have an invalid json format and you also need to append the json data into the tokens.json file, not into your own file.

This should be how the json file should look like, if you're adding your entry at the very bottom, then remove the comma at the end.

```json
"93057e283baef26fe8879f0a5b56d55893507cee6933c85babcb8db216": {
    "project": "FibonacciADA",
    "categories": ["TOM"],
    "socialLinks": {
      "website": "https://fibonacci-ada.com\",
      "twitter": "https://twitter.com/AdaFibonacci",
      "discord": "http://discord.gg/2NAQkd3BWg",
    }
},
```

**Comment by theuranus** [comment]
Added in:  https://github.com/minswap/verified-tokens/pull/23

**Comment by FibonacciADA** [comment]
Ahhh apologies for the mistake. I should have been more thorough with our submission. Thank you for adding either way! 
Can we please change category from 'meme' to 'DAO' or 'DeFi' please if 'TOM' is not accepted?

**Comment by theuranus** [comment]
> Ahhh apologies for the mistake. I should have been more thorough with our submission. Thank you for adding either way! 
> 
> Can we please change category from 'meme' to 'DAO' or 'DeFi' please if 'TOM' is not accepted? 

@FibonacciADA That's ok. Can you plz create an issue?

**Pull request closed without merging**
