### PR TITLE
Verify STRCH Token

### PR DESCRIPTION
**Pull request by abstractpotato**

### CODE REVIEW

**Comment by shadowkora** [comment]
Cannot find policyID in Twitter bio or anywhere on the website's landing page, please fix that so I can verify you.

Also if you can, please try to fix the PR code

**Comment by abstractpotato** [comment]
All policy ids for the project can be found here: [https://starch.one/assets](https://starch.one/assets) and the one for the token is here: [https://starch.one/assets#strch](https://starch.one/assets#strch) 

Could you please clarify what is the PR code?

**Comment by abstractpotato** [comment]
I've also added the policy id in the footer of the website. 
image

**Comment by shadowkora** [comment]
Verified in #635

**Pull request closed without merging**
