### PR TITLE
Update tokens.json

### PR DESCRIPTION
**Pull request by capitalismtoken**
Verification for $CAP from project CAPITALISM

### CODE REVIEW

**Comment by shadowkora** [comment]
Hey @capitalismtoken, please add a token logo in the cardano-token-registry as we require it to verify your token, thank you.

**Comment by shadowkora** [comment]
@capitalismtoken any update?

**Comment by capitalismtoken** [comment]
> @capitalismtoken any update?

Hello, I have been trying to update the code on the Cardano Foundation, but I have not received any responses or comments. However, my code had a "," in the wrong place, so I closed the old pull request and opened a new one today fixing that bug. I hope to receive some response about that update and instantly notice it here. Just in case, I leave you the link to the pull request https://github.com/cardano-foundation/cardano-token-registry/pull/3327#issue-1775230317.

Thanks in advance for your patience and cordiality.

**Comment by capitalismtoken** [comment]
Hi. It's done. I added logo to json file. If there is any other problem, pleas I will be happy to collaborate to solve it. Thanks

**Comment by shadowkora** [comment]
Added in #368

**Pull request closed without merging**
