### PR TITLE
Update tokens.json

### PR DESCRIPTION
**Pull request by avilsmeier**
Added $MAYZ token

### CODE REVIEW

**Comment by longngn** [comment]
> Added $MAYZ token

it's duplicated

**Comment by avilsmeier** [comment]
SO sorry about that.
Updated to remove duplicated entry.

**Comment by shadowkora** [comment]
@avilsmeier Please add your policyID either to your Twitter bio or somewhere on your landing page

**Comment by avilsmeier** [comment]
Hi, PolicyID has been added to Twitter bio and will be added shortly to our home page as well, thank you.

**Pull request merged**
