### PR TITLE
Add KWIC

### PR DESCRIPTION
**Pull request by cardanoshield**
Please verify KWIC.

### CODE REVIEW

**Comment by cardanoshield** [comment]
Just had the team put their official token policy ID in their twitter bio.

https://twitter.com/KeyboardWIC

**Comment by cardanoshield** [comment]
For context, I'm a member of the CSWAP team.  We added minswap liquidity on their behalf, and submitted the request, on their behalf.

**Comment by shadowkora** [comment]
@cardanoshield The KWIC token is missing its logo in Cardano Token Registry and also its name
vvcap 2023-11-22-01-06-06

**Comment by cardanoshield** [comment]
I reached out to the team and they are working on getting this sorted....will update once i hear back.

**Comment by shadowkora** [comment]
Logo and name still not fixed

**Comment by cardanoshield** [comment]
@shadowkora can we re-open this? The KWIC team finally got registered on Cardano Token registry and we'd like to re-open this.

**Comment by cardanoshield** [comment]
Actually, nevermind, I opened a new PR here, please address that here:

https://github.com/minswap/verified-tokens/pull/541

**Comment by cardanoshield** [comment]
new PR is here:

https://github.com/minswap/verified-tokens/pull/503

**Comment by cardanoshield** [comment]
New PR is here:

https://github.com/minswap/verified-tokens/pull/542

**Pull request closed without merging**
