### PR TITLE
added reitcircles

### PR DESCRIPTION
**Pull request by nilaysaha**
adding reit tokens for verification on minswap

### CODE REVIEW

**Comment by shadowkora** [comment]
No policyID on socials
@nilaysaha

**Comment by reitcircles** [comment]
> No policyID on socials @nilaysaha

what do you precisely mean ? Can you elaborate. Why is this PR being held back ?

**Comment by reitcircles** [comment]
I am compiling to check what the error is ...

**Comment by reitcircles** [comment]
The category was changed to RealFi and `npm run test` succeeds . It should work now.

**Comment by reitcircles** [comment]
Thanks.

**Pull request merged**
