### PR TITLE
Update tokens.json

### PR DESCRIPTION
**Pull request by mustardwithlemon**

### CODE REVIEW

**Comment by mustardwithlemon** [comment]
cannot share policy ID to public to avoid bot snipers

**Comment by shadowkora** [comment]
I assume the PolicyID in the PR is fake then? In that case I can't verify you, even if the PolicyID is correct, there is no pool for it.

**Comment by mustardwithlemon** [comment]
hello there is pool now

**Comment by shadowkora** [comment]
The pool doesn't meet the minimum TVL requirements @mustardwithlemon

**Pull request closed without merging**
