### PR TITLE
Create Added $OPOC

### PR DESCRIPTION
**Pull request by OpocDev**
Verify $OPOC token

[

  "4ed5b703c146c25c09516f4b83aab31f44f7c55cdc159866e49731534f504f43", 
{"project": "OPOC",
    "categories": ["MEME"],
    "socialLinks": {
      "discord": "https://discord.gg/6jxTJ8DuAY",
      "twitter": "https://twitter.com/OnlyOnCardano"
    }}
    
    
]

### CODE REVIEW

**Comment by shadowkora** [comment]
Please put your policyID into your twitter bio @OpocDev

**Comment by OpocDev** [comment]
Done. @shadowkora

**Comment by OpocDev** [comment]
Is there anything else we need to provide ? @shadowkora

**Comment by shadowkora** [comment]
Added in #477

**Pull request closed without merging**
