### PR TITLE
Adding 7 Token 

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
These are not rugg pull token !

### CODE REVIEW

**Comment by theuranus** [comment]
Thank you for your contributing, please resolve the conflicting file. Otherwise you can create an issue, we'll verify your token for you.

**Comment by GabrielMazzanti** [comment]
> 

Hey, Hmmm how can I create an issue ? I'm really a noob on github and programming ... :/

**Comment by GabrielMazzanti** [comment]
Can i create an issue ? Just in case i responded to the wrong person ☺️

Le lun. 5 déc. 2022 à 08:35, Nguyễn Thái Bảo ***@***.***> a
écrit :

**Comment by theuranus** [comment]
Duplicated https://github.com/minswap/verified-tokens/pull/59

**Pull request closed without merging**
