### PR TITLE
Verify ADA Empire Token

### PR DESCRIPTION
**Pull request by jshear**

### CODE REVIEW

**Comment by shadowkora** [comment]
Hey @jshear, all seems to be correct apart from a missing policyID from your socials (Twitter bio or landing page of your website) so I can't verify you unless you add the policyID to either of those

**Comment by jshear** [comment]
Hello @shadowkora the policy ID has been added to the Twitter bio. Please let me know if you need anything else. Thank you!

**Comment by jshear** [comment]
Hello @shadowkora! Just wanted to reach out again to confirm that you were able to find the policy ID on the Twitter bio.

**Comment by shadowkora** [comment]
Added in #460

**Pull request closed without merging**
