### PR TITLE
Add DERP

### PR DESCRIPTION
**Pull request by chafnan**

### CODE REVIEW

**Review by tvtduy59 — APPROVED** [review]
LGTM

**Comment by theuranus** [comment]
@chafnan your PR has failed the CI (Unexpected token `{` in JSON), please resolve it

**Review by theuranus — APPROVED** [review]

**Review by theuranus — COMMENTED** [review]
Failed CI. You can run `npm run test` before push ur code

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/136

**Pull request closed without merging**
