### PR TITLE
jukeboys token registration

### PR DESCRIPTION
**Pull request by mathieu2em**
policyID and tokenomics in their whitepaper : https://jukepaper.jukeboys.io/

### CODE REVIEW

**Comment by mathieu2em** [comment]
discloser : I am only sending this pull request for a customer. this token isnt my responsibility. I am not the owner or creator of this project or token.

**Comment by mathieu2em** [comment]
@longngn

**Comment by tvtduy59** [comment]
This project hasn't have pool on our DEX yet

**Comment by mathieu2em** [comment]
> This project hasn't have pool on our DEX yet

Could you please tell me what the project needs to do in order for my pull request to be accepted next time?

**Comment by mathieu2em** [comment]
ok found it. https://docs.minswap.org/faq/token-launching-and-farming/1.-token-listing

**Pull request closed without merging**
